services:
  compose-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "8080:18888"
    expose:
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"
    expose:
      - "1433"
    volumes:
      - type: "volume"
        target: "/var/opt/mssql"
        source: "apphost-feed4158f1-sql-data"
        read_only: false
    networks:
      - "aspire"
  rabbit:
    image: "docker.io/library/rabbitmq:4.1"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "${RABBIT_PASSWORD}"
    expose:
      - "5672"
    volumes:
      - type: "volume"
        target: "/var/lib/rabbitmq"
        source: "apphost-feed4158f1-rabbit-data"
        read_only: false
    networks:
      - "aspire"
  webapi:
    image: "${WEBAPI_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${WEBAPI_PORT}"
      ConnectionStrings__sqldata: "Server=sql,1433;User ID=sa;Password=${SQL_PASSWORD};TrustServerCertificate=true;Initial Catalog=sqldata"
      ConnectionStrings__rabbit: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      services__okta-api__default__0: "${OKTA_DOMAIN}"
      OKTA_DOMAIN: "${OKTA_DOMAIN}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "webapi"
    ports:
      - "${WEBAPI_PORT}"
    depends_on:
      sql:
        condition: "service_started"
      rabbit:
        condition: "service_started"
    networks:
      - "aspire"
  blazorserver:
    image: "${BLAZORSERVER_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${BLAZORSERVER_PORT}"
      services__webapi__http__0: "http://webapi:${WEBAPI_PORT}"
      ConnectionStrings__rabbit: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      services__okta-api__default__0: "${OKTA_DOMAIN}"
      OKTA_DOMAIN: "${OKTA_DOMAIN}"
      OKTA_CLIENT_ID: "${OKTA_CLIENT_ID}"
      OKTA_CLIENT_SECRET: "${OKTA_CLIENT_SECRET}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "blazorserver"
    ports:
      - "${BLAZORSERVER_PORT}"
    depends_on:
      webapi:
        condition: "service_started"
      rabbit:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  apphost-feed4158f1-sql-data:
    driver: "local"
  apphost-feed4158f1-rabbit-data:
    driver: "local"
